### ISSUE TITLE
[창의학기제]일정 및 주차별 보고서 가이드

### ISSUE THREAD

**Issue by seraaaayeo** [seraaaayeo/SellyDev#21]
## 창의학기제 일정

* 종강 : 6/19 (금)
* 중간 간담회 : 5/7 (목)
* 보고서 제출 : 6/25 (목) 17:00 까지
* 최종 발표 : 06/29 (월) ~ 6/30 (화)

#### 여기에 작성한 주차별 학습 목표 가지고 주차별 보고서 작성합시다!!! 적어도 10개 써야함!!

1. ~프로젝트 진행 방향 설계(월별 목표, 개발 프로세스 결정, 모임 시간 결정), 자율주행 프레임워크 분석 및 공부~

2. ~‘Selly'   워크플로우 설계 : 사용할 센서 및 센서 활용법 결정, 적용할 알고리즘 토론, 하드웨어 및 소프트웨어 구상 및 설계~

3. ~센서 제어를 위한 연습용 로봇 설계 및 라이다 센서, 아두이노 센서 제어 테스트.   연습용 로봇으로 주행 컨트롤 테스트~

4. ~구글 오픈 소프트웨어 Catographer를 사용한 SLAM 구현~

5. ~하드웨어 제작 및 센서 부착, 간단한 모터 주행 테스트~

6. ~image segmentation기반 인도 구분 모델 구축~

7. ~visual SLAM 기반의 알고리즘을 사용하여 localization 및   mapping을 통한 지도 구축~

8. ~depth vision 보정 알고리즘 적용~

9. ~image segmentation + depth 기반 주행 경로 결정 알고리즘 설계~

10. ~네트워크 안정화 + 모델 경량화~

11. 내비게이션을 위한 GPS 보정 알고리즘 제안 및 경로 설정

12. 설계한 알고리즘을 바탕으로 최적의 경로를 찾기 위한 navigation 테스트

13. 물체 회피 테스트

14. 서비스 구현

15. 최종 테스트 보완, 유지보수

**Comment by JunHyeok96** [comment]
6, 8, 9, 10 작성 완료
